### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by a27cheung**
Adding 'commercially' licensed to up our game.

### CODE REVIEW

**Review by a27cheung — COMMENTED** [review]
Added distinguishing comments to help set us apart

**Comment by owahltinez** [comment]
Can you please update this to match what's on BigQuery?

**Comment by a27cheung** [comment]
Yes, will do! Apologies for delay.

**Review by a27cheung — COMMENTED** [review]
Merged conflicts for V3 schema changes

**Comment by a27cheung** [comment]
merged all conflicts for v2 to v3 changes.

**Comment by owahltinez** [comment]
Are you going to keep this PR separate or do the changes as part of the other one?

**Comment by owahltinez** [comment]
Closing in favor of #490

**Pull request closed without merging**
