### PR TITLE
Add total recovered field to documentation for epidemiology table.

### PR DESCRIPTION
**Pull request by geening**

### CODE REVIEW

**Comment by geening** [comment]
Any idea why this documentation change made the pipeline fail?  Or did it?
https://github.com/GoogleCloudPlatform/covid-19-open-data/actions/runs/380109291

**Comment by themonk911** [comment]
It looks like it failed for an unrelated reason, you can see the logs for the test results on github.

```
RuntimeError: PcmDpcL3DataSource from epidemiology pipeline failed with options {'name': 'pipelines.epidemiology.it_authority.PcmDpcL3DataSource', 'fetch': [{'url': 'https://raw.github.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-province.json'}], 'test': {'location_key_match': 'IT_.+_.+'}, 'automation': {'job_group': 'all', 'deferred': True}} and using metadata keys ['IT_34_VR', 'IT_57_PU', 'IT_21_BI', 'IT_52_PO', 'IT_67_IS', 'IT_75_BA', 'IT_25_MN', 'IT_65_AQ', 'IT_57_AN', 'IT_52_LU', 'IT_55_PG', 'IT_82_RG', 'IT_88_CA', 'IT_25_LO', 'IT_21_VC', 'IT_36_UD', 'IT_34_RO', 'IT_34_VE', 'IT_42_SP', 'IT_25_BG', 'IT_45_RN', 'IT_72_SA', 'IT_21_CN', 'IT_72_BN']
```

**Review by owahltinez — APPROVED** [review]
LGTM. The failure is probably just a transient issue.

**Comment by owahltinez** [comment]
This is the reason behind the test failure:
image

There's already a bug for it: https://github.com/pcm-dpc/COVID-19/issues/943. Interestingly, it looks like these JSON files are being manually generated...

**Pull request merged**
